[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/yt-callback"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
